### ISSUE TITLE
Intermediate elasticsearch dir prevents from installing from ZIP

### ISSUE THREAD

**Issue by indigo423** [OpenNMS/elasticsearch-drift-plugin#9]
I've downloaded the ZIP file compatible with Elasticsearch 6.5.4 from the release page and tried to install it I get the following error message:

```
 ./elasticsearch-plugin install file:///apps_nms/InstallFiles/elasticsearch-drift-plugin-1.1.0-SNAPSHOT.zip
-> Downloading file:///apps_nms/InstallFiles/elasticsearch-drift-plugin-1.1.0-SNAPSHOT.zip
[=================================================] 100%
ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.
```

The ZIP file should be build without the intermediate directory "elasticsearch".

**Comment by mmahacek** [comment]
Same thing happened to me when testing 1.1.0-SNAPSHOT.  Can confirm repackaging without a folder installs on my test server.

**Comment by j-white** [comment]
Fixed with https://github.com/OpenNMS/elasticsearch-drift-plugin/pull/10
